[global]
dataFrameSerialization = "legacy"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4A7C59"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E8F5E8"
textColor = "#2D5016"
font = "sans serif"